require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WineriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Winery. As you add validations to Winery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WineriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all wineries as @wineries" do
      winery = Winery.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:wineries)).to eq([winery])
    end
  end

  describe "GET #show" do
    it "assigns the requested winery as @winery" do
      winery = Winery.create! valid_attributes
      get :show, {:id => winery.to_param}, valid_session
      expect(assigns(:winery)).to eq(winery)
    end
  end

  describe "GET #new" do
    it "assigns a new winery as @winery" do
      get :new, {}, valid_session
      expect(assigns(:winery)).to be_a_new(Winery)
    end
  end

  describe "GET #edit" do
    it "assigns the requested winery as @winery" do
      winery = Winery.create! valid_attributes
      get :edit, {:id => winery.to_param}, valid_session
      expect(assigns(:winery)).to eq(winery)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Winery" do
        expect {
          post :create, {:winery => valid_attributes}, valid_session
        }.to change(Winery, :count).by(1)
      end

      it "assigns a newly created winery as @winery" do
        post :create, {:winery => valid_attributes}, valid_session
        expect(assigns(:winery)).to be_a(Winery)
        expect(assigns(:winery)).to be_persisted
      end

      it "redirects to the created winery" do
        post :create, {:winery => valid_attributes}, valid_session
        expect(response).to redirect_to(Winery.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved winery as @winery" do
        post :create, {:winery => invalid_attributes}, valid_session
        expect(assigns(:winery)).to be_a_new(Winery)
      end

      it "re-renders the 'new' template" do
        post :create, {:winery => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested winery" do
        winery = Winery.create! valid_attributes
        put :update, {:id => winery.to_param, :winery => new_attributes}, valid_session
        winery.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested winery as @winery" do
        winery = Winery.create! valid_attributes
        put :update, {:id => winery.to_param, :winery => valid_attributes}, valid_session
        expect(assigns(:winery)).to eq(winery)
      end

      it "redirects to the winery" do
        winery = Winery.create! valid_attributes
        put :update, {:id => winery.to_param, :winery => valid_attributes}, valid_session
        expect(response).to redirect_to(winery)
      end
    end

    context "with invalid params" do
      it "assigns the winery as @winery" do
        winery = Winery.create! valid_attributes
        put :update, {:id => winery.to_param, :winery => invalid_attributes}, valid_session
        expect(assigns(:winery)).to eq(winery)
      end

      it "re-renders the 'edit' template" do
        winery = Winery.create! valid_attributes
        put :update, {:id => winery.to_param, :winery => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested winery" do
      winery = Winery.create! valid_attributes
      expect {
        delete :destroy, {:id => winery.to_param}, valid_session
      }.to change(Winery, :count).by(-1)
    end

    it "redirects to the wineries list" do
      winery = Winery.create! valid_attributes
      delete :destroy, {:id => winery.to_param}, valid_session
      expect(response).to redirect_to(wineries_url)
    end
  end

end
